component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./bin/org/.*
- ./bin/org/javacc/.*
- ./bin/org/javacc/jjdoc/.*
- ./bin/org/javacc/jjdoc/test/.*
- ./bin/org/javacc/jjtree/.*
- ./bin/org/javacc/parser/.*
- ./bin/org/javacc/parser/test/.*
- ./bin/org/javacc/utils/.*
- ./bootstrap/.*
- ./examples/.*
- ./examples/CORBA-IDL/.*
- ./examples/GUIParsing/.*
- ./examples/GUIParsing/ParserVersion/.*
- ./examples/GUIParsing/TokenMgrVersion/.*
- ./examples/Interpreter/.*
- ./examples/JJTreeExamples/.*
- ./examples/JavaCCGrammar/.*
- ./examples/JavaGrammars/.*
- ./examples/JavaGrammars/1.5/.*
- ./examples/Lookahead/.*
- ./examples/MailProcessing/.*
- ./examples/Obfuscator/.*
- ./examples/Obfuscator/input/.*
- ./examples/Obfuscator/input/package1/.*
- ./examples/Obfuscator/input/package2/.*
- ./examples/SimpleExamples/.*
- ./examples/Transformer/.*
- ./examples/VTransformer/.*
- ./examples/bin/.*
- ./examples/bin/package1/.*
- ./examples/bin/package2/.*
- ./lib/.*
- ./lib/junit3.8.1/.*
- ./templates/.*
- ./test/.*
- ./test/bin/.*
- ./test/exceptions/.*
- ./test/imports/.*
- ./test/javaFileGeneration/.*
- ./test/javaFileGeneration/expected/.*
- ./test/javaFileGeneration/expected/no-keep-line/.*
- ./test/javaFileGeneration/expected/non-static/.*
- ./test/javaFileGeneration/expected/not-public/.*
- ./test/javaFileGeneration/expected/static/.*
- ./test/javaFiles/.*
- ./test/javaFiles/lib/.*
- ./test/javaFiles/lib/junit3.8.1/.*
- ./test/javacodeLA/.*
- ./test/lineNumbers/.*
- ./test/lom/.*
- ./test/newToken/.*
- ./www/.*
- ./www/doc/.*
